<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
  <info organisation="com.pramora.testable" module="jv-406" revision="1.0.0"/>

  <configurations>
    <conf name="compile" description="compile-time dependencies"/>
    <conf name="test" extends="compile" description="test-only dependencies"/>
    <conf name="provided" description="supplied by the container"/>
  </configurations>

  <dependencies>
    <dependency org="commons-collections" name="commons-collections" rev="3.2.1" conf="compile->default"/>
    <dependency org="org.apache.commons" name="commons-text" rev="1.9" conf="compile->default"/>
    <dependency org="com.fasterxml.jackson.core" name="jackson-databind" rev="2.9.10.1" conf="compile->default"/>
    <dependency org="log4j" name="log4j" rev="1.2.17" conf="compile->default"/>
    <dependency org="org.yaml" name="snakeyaml" rev="1.30" conf="compile->default"/>
    <dependency org="junit" name="junit" rev="4.13.2" conf="test-&gt;default"/>
    <dependency org="javax.servlet" name="javax.servlet-api" rev="3.1.0" conf="provided-&gt;default"/>
  </dependencies>
</ivy-module>
